name: Node.js CI

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: echo "----- `node -v` -----"
    - run: echo "----- `npm -v` -----"
    - run: echo "----- install dependencies -----"
    - run: npm install
    - run: echo "----- build -----"
    - run: npm run build
    - run: echo "----- deploy -----"
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './docs/.vitepress/dist'
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
    - run: echo "----- deploy done -----"
